[theme]
primaryColor="#1e3d59"
backgroundColor="#f8f9fa"
secondaryBackgroundColor="#e9ecef"
textColor="#212529"

[server]
enableCORS=false
enableXsrfProtection=true

[browser]
gatherUsageStats=false

