[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyMaxRetries = 5
GOOGLE_APPLICATION_CREDENTIALS=credentials.json
OAUTHLIB_INSECURE_TRANSPORT=1  # Solo si es necesario para desarrollo

[deploy.envs]
PORT = "8501"
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_ENABLECORS = "true"
PYTHONUNBUFFERED = "1"
