[build]
builder = "nixpacks"

[deploy]
startCommand = "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyMaxRetries = 3

[deploy.envs]
STREAMLIT_SERVER_PORT = "$PORT"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_MAX_UPLOAD_SIZE = "5"
PYTHONUNBUFFERED = "1"
STREAMLIT_SERVER_ENABLEXSRFPROTECTION = "false"
STREAMLIT_SERVER_ENABLECORS = "false"